# Generated by Django 3.2.25 on 2025-06-22 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0067_auto_20201230_1237'),
        ('tasks', '0013_auto_20200615_0811'),
        ('userstories', '0022_userstory_in_sprint_backlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='meeting date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_meetings', to='projects.project', verbose_name='project')),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_meetings', to='milestones.milestone', verbose_name='sprint')),
            ],
            options={
                'verbose_name': 'Daily Meeting',
                'verbose_name_plural': 'Daily Meetings',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('project', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SprintReviewEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milestones.milestone')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SprintRetrospective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('positives', models.TextField(blank=True, null=True)),
                ('improvements', models.TextField(blank=True, null=True)),
                ('actions', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sprint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retrospective', to='milestones.milestone')),
            ],
        ),
        migrations.CreateModel(
            name='SprintClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sprint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closure', to='milestones.milestone')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='selected_task', to='tasks.task')),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userstories.userstory')),
            ],
        ),
        migrations.CreateModel(
            name='DailyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yesterday_work', models.TextField(help_text='Describe what you accomplished yesterday', verbose_name='What did you do yesterday?')),
                ('today_plan', models.TextField(help_text='Describe what you plan to work on today', verbose_name='What will you do today?')),
                ('blockers', models.TextField(blank=True, help_text='Describe any impediments or blockers', null=True, verbose_name='Any blockers?')),
                ('mood', models.CharField(choices=[('great', 'Great 😊'), ('good', 'Good 🙂'), ('neutral', 'Neutral 😐'), ('bad', 'Bad 😕'), ('terrible', 'Terrible 😞')], default='neutral', max_length=20, verbose_name='Team member mood')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='sprint_execution.dailymeeting', verbose_name='daily meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_responses', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Daily Response',
                'verbose_name_plural': 'Daily Responses',
                'ordering': ['-created_at'],
                'unique_together': {('meeting', 'user')},
            },
        ),
    ]
