# Generated by Django 3.2.25 on 2025-06-24 00:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0003_alter_milestone_closed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sprint_execution', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprintreviewentry',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='sprintreviewentry',
            old_name='feedback',
            new_name='general_feedback',
        ),
        migrations.RenameField(
            model_name='sprintreviewentry',
            old_name='approved',
            new_name='sprint_approved',
        ),
        migrations.RemoveField(
            model_name='sprintretrospective',
            name='actions',
        ),
        migrations.RemoveField(
            model_name='sprintretrospective',
            name='improvements',
        ),
        migrations.RemoveField(
            model_name='sprintretrospective',
            name='positives',
        ),
        migrations.AddField(
            model_name='sprintretrospective',
            name='action_items',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='sprintretrospective',
            name='commitment_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='sprintretrospective',
            name='previous_actions_completed',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='sprintretrospective',
            name='team_mood',
            field=models.CharField(choices=[('terrible', 'Terrible 😞'), ('bad', 'Malo 😕'), ('neutral', 'Neutral 😐'), ('good', 'Bueno 🙂'), ('great', 'Excelente 😊')], default='neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='sprintretrospective',
            name='to_improve',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='sprintretrospective',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sprintretrospective',
            name='velocity_achieved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sprintretrospective',
            name='went_well',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='sprintreviewentry',
            name='code_quality_rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='sprintreviewentry',
            name='completed_stories_feedback',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='sprintreviewentry',
            name='functionality_rating',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='sprintreviewentry',
            name='requires_changes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sprintreviewentry',
            name='satisfaction_level',
            field=models.IntegerField(choices=[(1, 'Muy Insatisfecho'), (2, 'Insatisfecho'), (3, 'Neutral'), (4, 'Satisfecho'), (5, 'Muy Satisfecho')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprintreviewentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='sprintreviewentry',
            unique_together={('sprint', 'user')},
        ),
    ]
