# Generated by Django 3.2.25 on 2025-02-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0021_auto_20201202_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='in_sprint_backlog',
            field=models.BooleanField(default=False),
        ),
    ]
