# Generated by Django 3.2.25 on 2025-06-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0002_remove_milestone_watchers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='closed',
            field=models.BooleanField(blank=True, default=False, verbose_name='is closed'),
        ),
    ]
