# Generated by Django 3.2.25 on 2025-02-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userstories', '0022_userstory_in_sprint_backlog'),
        ('planning_poker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningsession',
            name='user_stories',
            field=models.ManyToManyField(blank=True, related_name='planning_sessions', to='userstories.UserStory'),
        ),
    ]
