# Generated by Django 3.2.25 on 2025-06-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning_poker', '0002_planningsession_user_stories'),
    ]

    operations = [
        migrations.AddField(
            model_name='planningsession',
            name='name',
            field=models.CharField(default='Sesión sin nombre', max_length=255),
        ),
    ]
